name: Build EXE
on:
  workflow_dispatch: # Позволяет запускать сборку вручную

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: install dependencies
        run: |
          cd frontend
          npm install
          cd ..

      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v__VERSION__ # Это создаст релиз
          releaseName: "Jarvis v__VERSION__"
          releaseBody: "Сборка JARVIS для Windows"
          releaseDraft: true
          prerelease: false
