name: Build EXE
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable

      - name: build prep
        run: |
          cd frontend
          npm install
          # Принудительно заменяем команду билда, если она не сохранилась
          npm pkg set scripts.build="vite build"
          cd ..

      - name: build tauri app
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: v1.0.0
          releaseName: "Jarvis v1.0.0"
          releaseDraft: true
          prerelease: false
